/* tslint:disable */
/* eslint-disable */
/**
 * Nullable Test API - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { alovaInstance, $$userConfigMap } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;

type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface Pet {
  /**
   * Pet ID
   * ---
   */

  id?: number | null;
  /**
   * Pet Name
   * ---
   */

  name: string;
  /**
   * Pet Status
   * ---
   */

  status?: 'available' | 'pending' | 'sold' | null;
  /**
   * Pet Tags
   * ---
   */

  tags?: Tag[] | null;
}
export interface Tag {
  id?: number;
  name?: string;
}

declare global {
  interface Apis {
    pet: {
      /**
       * ---
       *
       * [POST] Add a new pet
       *
       * **path:** /pet
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // [title] Pet ID
       *   id?: number | null
       *   // [title] Pet Name
       *   name: string
       *   // [title] Pet Status
       *   status?: "available" | "pending" | "sold" | null
       *   // [title] Pet Tags
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   tags?: Array<{
       *   id?: number
       *   name?: string
       *   }> | null
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [title] Pet ID
       *   id?: number | null
       *   // [title] Pet Name
       *   name: string
       *   // [title] Pet Status
       *   status?: "available" | "pending" | "sold" | null
       *   // [title] Pet Tags
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   tags?: Array<{
       *   id?: number
       *   name?: string
       *   }> | null
       * }
       * ```
       */
      addPet<
        Config extends Alova2MethodConfig<Pet> & {
          data: Pet;
        }
      >(
        config: Config
      ): Alova2Method<Pet, 'Apis.pet.addPet', Config>;
    };
  }

  var Apis: Apis;
}

export {};
