/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI - version 1.0.0
 *
 * This is a sample server Petstore server. For this sample, you can use the api key &#x60;special-key&#x60; to test the authorization filters.
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import { createAlova } from 'alova';
import fetchAdapter from 'alova/fetch';
import { createApis, mountApis, withConfigType } from './createApis';

export const alovaInstance = createAlova({
  baseURL: '',
  requestAdapter: fetchAdapter(),
  beforeRequest: method => {},
  responded: res => {
    return res.json();
  }
});

export const $$userConfigMap = withConfigType({});

const Apis = createApis(alovaInstance, $$userConfigMap);

mountApis(Apis);

export { Apis };
