packages:
  - test/*
  - packages/*

catalog:
  '@alova/adapter-xhr': ^2.2.0
  '@alova/mock': ^2.0.17
  '@antfu/ni': ^25.0.0
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.5
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@eslint/eslintrc': ^3.3.1
  '@jsonrpc-rx/client': ^0.2.2
  '@jsonrpc-rx/server': ^0.2.1
  '@types/fs-extra': ^11.0.4
  '@types/js-yaml': ^4.0.9
  '@types/lodash': ^4.17.20
  '@types/mocha': ^10.0.10
  '@types/node': ^24.0.14
  '@types/sinon': ^17.0.4
  '@types/swagger2openapi': ^7.0.4
  '@unocss/preset-web-fonts': ^66.3.3
  '@vicons/ionicons5': ^0.13.0
  '@vitejs/plugin-vue-jsx': ^5.0.1
  '@vitest/coverage-v8': ^3.2.4
  '@vscode/test-electron': ^2.5.2
  '@vscode/vsce': ^3.6.0
  alova: ^3.3.4
  commander: ^14.0.0
  commitizen: ^4.3.1
  coveralls: ^3.1.1
  cz-conventional-changelog: ^3.3.0
  dts-bundle-generator: ^9.5.1
  esbuild: ^0.25.6
  fast-glob: ^3.3.3
  fs-extra: ^11.3.0
  glob: ^11.0.3
  globals: ^16.3.0
  handlebars: ^4.7.8
  highlight.js: ^11.11.1
  husky: ^9.1.7
  import-fresh: ^3.3.1
  js-yaml: ^4.1.0
  lodash: ^4.17.21
  memfs: ^4.17.2
  mocha: ^11.7.1
  msw: ^2.10.4
  naive-ui: ^2.42.0
  ncp: ^2.0.0
  npm-run-all2: ^8.0.4
  openapi: ^1.0.1
  openapi-types: ^12.1.3
  ora: ^8.2.0
  ovsx: ^0.10.5
  prettier: ^3.6.2
  rimraf: ^6.0.1
  sinon: ^21.0.0
  swagger2openapi: ^7.0.8
  tsc-alias: ^1.8.16
  tslib: ^2.8.1
  tsx: ^4.20.3
  type-fest: ^4.41.0
  vscode-ext-gen: ^1.1.0
  zod: ^3.25.68-alpha.11
  zod-validation-error: ^3.5.3

catalogs:
  build:
    '@czhlin/vite-plugin-vscode': ^4.3.0
    '@intlify/unplugin-vue-i18n': ^6.0.8
    '@shikijs/markdown-it': ^3.8.1
    '@unocss/eslint-config': ^66.3.3
    '@vitejs/plugin-vue': ^6.0.0
    markdown-it-link-attributes: ^4.0.1
    unocss: ^66.3.3
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.8.0
    unplugin-vue-markdown: ^29.1.0
    unplugin-vue-router: ^0.14.0
    vite: ^7.0.5
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.3.0
    vite-plugin-vue-devtools: ^7.7.7
    vite-plugin-vue-layouts: ^0.11.0
  dev:
    '@antfu/eslint-config': ^4.17.0
    '@iconify-json/carbon': ^1.2.10
    '@tomjs/tsconfig': ^2.0.0
    '@vue/test-utils': ^2.4.6
    eslint: ^9.31.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.2
    taze: ^19.1.0
    typescript: ^5.8.3
    vitest: ^3.2.4
    vue-tsc: ^3.0.2
  frontend:
    '@tomjs/vscode-webview': ^2.0.2
    '@unhead/vue': ^2.0.12
    '@unocss/reset': ^66.3.3
    '@vueuse/core': ^13.5.0
    nprogress: ^0.2.0
    pinia: ^3.0.3
    query-string: ^9.2.2
    reactive-vscode: ^0.3.1
    vue: ^3.5.17
    vue-i18n: ^11.1.10
    vue-router: ^4.5.1
  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/nprogress': ^0.2.3
    '@types/vscode-webview': ^1.57.5

ignoredBuiltDependencies:
  - '@vscode/vsce-sign'
  - keytar
  - msw

onlyBuiltDependencies:
  - cypress
  - esbuild
