// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = 'worma'
export const name = 'worma-vscode'
export const version = '0.0.1'
export const displayName = 'Worma'
export const description = 'Generate and search APIs without API documentation any more'
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey
  = | 'worma.refresh'
    | 'worma.generateApi.force'
    | 'worma.create.config'
    | 'worma.apiDocs.refresh'
    | 'worma.snippetSearch.open'
    | 'worma.snippetSearch.insert'
    | 'worma.snippetSearch.showHelp'

/**
 * Commands map registered by `worma.worma-vscode`
 */
export const commands = {
  /**
   * Generate APIs
   * @value `worma.refresh`
   */
  wormaRefresh: 'worma.refresh',
  /**
   * Force Generate APIs
   * @value `worma.generateApi.force`
   */
  wormaGenerateApiForce: 'worma.generateApi.force',
  /**
   * Create worma config
   * @value `worma.create.config`
   */
  wormaCreateConfig: 'worma.create.config',
  /**
   * Refresh View
   * @value `worma.apiDocs.refresh`
   */
  wormaApiDocsRefresh: 'worma.apiDocs.refresh',
  /**
   * 打开代码片段搜索
   * @value `worma.snippetSearch.open`
   */
  wormaSnippetSearchOpen: 'worma.snippetSearch.open',
  /**
   * 插入代码片段
   * @value `worma.snippetSearch.insert`
   */
  wormaSnippetSearchInsert: 'worma.snippetSearch.insert',
  /**
   * 显示快捷键帮助
   * @value `worma.snippetSearch.showHelp`
   */
  wormaSnippetSearchShowHelp: 'worma.snippetSearch.showHelp',
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey = 'worma.autoUpdate'

export interface ConfigKeyTypeMap {
  'worma.autoUpdate': boolean | { launchEditor?: boolean, interval?: number }
}

export interface ConfigShorthandMap {
  autoUpdate: 'worma.autoUpdate'
}

export interface ConfigShorthandTypeMap {
  autoUpdate: boolean | { launchEditor?: boolean, interval?: number }
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T
  default: ConfigKeyTypeMap[T]
}

/**
 * Configs map registered by `worma.worma-vscode`
 */
export const configs = {
  /**
   * Whether to automatically update APIs.
   * @key `worma.autoUpdate`
   * @default `true`
   */
  autoUpdate: 'worma.autoUpdate',
} satisfies Record<string, ConfigKey>

export interface ScopedConfigKeyTypeMap {
  autoUpdate: boolean | { launchEditor?: boolean, interval?: number }
}

export const scopedConfigs = {
  scope: 'worma-vscode',
  defaults: {
    autoUpdate: true,
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  worma: {
    autoUpdate: boolean | { launchEditor?: boolean, interval?: number }
  }
}
