// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = 'worma'
export const name = 'worma-vscode'
export const version = '0.2.1'
export const displayName = 'Worma'
export const description = 'Generate and search APIs without API documentation any more'
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey
  = | 'worma.refresh'
    | 'worma.generateApi.force'
    | 'worma.create.config'
    | 'worma.apiDocs.refresh'
    | 'worma.snippetSearch.open'
    | 'worma.snippetSearch.insert'
    | 'worma.snippetSearch.showHelp'

/**
 * Commands map registered by `worma.worma-vscode`
 */
export const commands = {
  /**
   * Generate APIs
   * @value `worma.refresh`
   */
  refresh: 'worma.refresh',
  /**
   * Force Generate APIs
   * @value `worma.generateApi.force`
   */
  generateApiForce: 'worma.generateApi.force',
  /**
   * Create worma config
   * @value `worma.create.config`
   */
  createConfig: 'worma.create.config',
  /**
   * Refresh View
   * @value `worma.apiDocs.refresh`
   */
  apiDocsRefresh: 'worma.apiDocs.refresh',
  /**
   * Open Snippet Search
   * @value `worma.snippetSearch.open`
   */
  snippetSearchOpen: 'worma.snippetSearch.open',
  /**
   * Insert Snippet
   * @value `worma.snippetSearch.insert`
   */
  snippetSearchInsert: 'worma.snippetSearch.insert',
  /**
   * Show Shortcut Help
   * @value `worma.snippetSearch.showHelp`
   */
  snippetSearchShowHelp: 'worma.snippetSearch.showHelp',
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey
  = | 'worma.enableViewApiLens'

export interface ConfigKeyTypeMap {
  'worma.enableViewApiLens': boolean
}

export interface ConfigShorthandMap {
  enableViewApiLens: 'worma.enableViewApiLens'
}

export interface ConfigShorthandTypeMap {
  enableViewApiLens: boolean
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T
  default: ConfigKeyTypeMap[T]
}

/**
 * Configs map registered by `worma.worma-vscode`
 */
export const configs = {
  /**
   *
   * @key `worma.enableViewApiLens`
   * @default `true`
   * @type `boolean`
   */
  enableViewApiLens: {
    key: 'worma.enableViewApiLens',
    default: true,
  } as ConfigItem<'worma.enableViewApiLens'>,
}

export interface ScopedConfigKeyTypeMap {
  enableViewApiLens: boolean
}

export const scopedConfigs = {
  scope: 'worma',
  defaults: {
    enableViewApiLens: true,
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  worma: {
    enableViewApiLens: boolean
  }
}

export interface NestedScopedConfigs {
  enableViewApiLens: boolean
}
