/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Generator - version 3.0.57
 *
 * This is an online swagger codegen server.  You can find out more at https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
/// <reference types='./globals.d.ts' />

const apiDefinitions = {
  'clients.customClients': ['GET', '/clients/suffix'],
  'clients.generateBundle': ['POST', '/model'],
  'documentation.customClients': ['GET', '/clients/suffix'],
  'documentation.documentationLanguages': ['GET', '/documentation']
} as const;

export default apiDefinitions;
