/* tslint:disable */

/**
 * Swagger Generator - version 3.0.57
 *
 * This is an online swagger codegen server.  You can find out more at https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import { createAlova } from 'alova'
import fetchAdapter from 'alova/fetch'
import { createApis, mountApis, withConfigType } from './createApis'

export const alovaInstance = createAlova({
  baseURL: '/api1',
  requestAdapter: fetchAdapter(),
  beforeRequest: (_method) => {},
  responded: (res) => {
    return res.json()
  },
})

export const $$userConfigMap = withConfigType({})

const Apis = createApis(alovaInstance, $$userConfigMap)

mountApis(Apis)

export { Apis }
