/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Generator - version 3.0.57
 *
 * This is an online swagger codegen server.  You can find out more at https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { alovaInstance, $$userConfigMap } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;

type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface AuthorizationValue {
  /**
   * Authorization value
   */

  value?: string;
  /**
   * Authorization key
   */

  keyName?: string;
  /**
   * Authorization type
   */

  type?: 'query' | 'header';
}
export interface GenerationRequest {
  /**
   * language
   * ---
   * language to generate (required)456
   */

  lang: string;
  /**
   * spec in json format. . Alternative to `specURL`
   */

  spec?: object;
  /**
   * URL of the spec in json format. Alternative to `spec`
   */

  specURL?: string;
  /**
   * type of the spec
   */

  type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG';
  /**
   * codegen version to use
   */

  codegenVersion?: 'V2' | 'V3';
  options?: Options;
}
export interface Options {
  /**
   * authorization
   * ---
   * adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
   */

  auth?: string;
  /**
   * authorization
   * ---
   * adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
   */

  authorizationValue?: AuthorizationValue;
  /**
   * api package
   * ---
   * package for generated api classes
   */

  apiPackage?: string;
  /**
   * Template Version
   * ---
   * template version for generation
   */

  templateVersion?: string;
  /**
   * model package
   * ---
   * package for generated models
   */

  modelPackage?: string;
  /**
   * model name prefix
   * ---
   * Prefix that will be prepended to all model names. Default is the empty string.
   */

  modelNamePrefix?: string;
  /**
   * model name suffix
   * ---
   * PrefixSuffix that will be appended to all model names. Default is the empty string.
   */

  modelNameSuffix?: string;
  /**
   * System Properties
   * ---
   * sets specified system properties in key/value format
   */

  systemProperties?: Record<string, string>;
  /**
   * instantiation types
   * ---
   * sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
   */

  instantiationTypes?: Record<string, string>;
  /**
   * type mappings
   * ---
   * sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
   */

  typeMappings?: Record<string, string>;
  /**
   * additional properties
   * ---
   * sets additional properties that can be referenced by the mustache templates in key/value format.
   */

  additionalProperties?: Record<string, object>;
  /**
   * language specific primitives
   * ---
   * specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
   */

  languageSpecificPrimitives?: string[];
  /**
   * import mappings
   * ---
   * specifies mappings between a given class and the import that should be used for that class in key/value format.
   */

  importMappings?: Record<string, string>;
  /**
   * invoker package
   * ---
   * root package for generated code
   */

  invokerPackage?: string;
  /**
   * group id
   * ---
   * groupId in generated pom.xml
   */

  groupId?: string;
  /**
   * artifact id
   * ---
   * artifactId in generated pom.xml
   */

  artifactId?: string;
  /**
   * artifact version
   * ---
   * artifact version generated in pom.xml
   */

  artifactVersion?: string;
  /**
   * library
   * ---
   * library template (sub-template)
   */

  library?: string;
  /**
   * git user id
   * ---
   * Git user ID, e.g. swagger-api.
   */

  gitUserId?: string;
  /**
   * git repo id
   * ---
   * Git repo ID, e.g. swagger-codegen.
   */

  gitRepoId?: string;
  /**
   * release note
   * ---
   * Release note, default to 'Minor update'.
   */

  releaseNote?: string;
  /**
   * http user agent
   * ---
   * HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
   */

  httpUserAgent?: string;
  /**
   * reserved words mappings
   * ---
   * pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
   */

  reservedWordsMappings?: Record<string, string>;
  /**
   * ignore file override location
   * ---
   * Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
   */

  ignoreFileOverride?: string;
  /**
   * remove prefix of the operationId
   * ---
   * Remove prefix of operationId, e.g. config_getId => getId
   */

  removeOperationIdPrefix?: boolean;
  skipOverride?: boolean;
}

declare global {
  interface Apis {
    clients: {
      /**
       * ---
       *
       * [GET] Deprecated, use '/{type}/{version}' instead. List generator languages of type 'client' or 'documentation' for given codegen version (defaults to V3)
       *
       * **path:** /clients/suffix
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // client token
       *   token?:string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // generator version used by codegen engine
       *   version?:"V2" | "V3"
       *   // flag to only return languages of type `client`
       *   clientOnly?:boolean
       *   // client id
       *   id:number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = (string)[]
       * ```
       */
      customClients<
        Config extends Alova2MethodConfig<string[]> & {
          pathParams: {
            /**
             * client token
             */

            token?: string;
          };
          params: {
            /**
             * generator version used by codegen engine
             */

            version?: 'V2' | 'V3';
            /**
             * flag to only return languages of type `client`
             */

            clientOnly?: boolean;
            /**
             * client id
             */

            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<string[], 'clients.customClients', Config>;
      /**
       * ---
       *
       * [POST] 你好Generates the intermediate model ("bundle") and returns it as a JSON. body.
       *
       * **path:** /model
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   attr1?:string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [title] language
       *   // language to generate (required)456
       *   lang:string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?:object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?:string
       *   // type of the spec
       *   type?:"CLIENT" | "SERVER" | "DOCUMENTATION" | "CONFIG"
       *   // codegen version to use
       *   codegenVersion?:"V2" | "V3"
       *   options?:{
       *   // [title] authorization
       *   // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *   auth?:string
       *   // [title] authorization
       *   // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *   authorizationValue?:{
       *   // Authorization value
       *   value?:string
       *   // Authorization key
       *   keyName?:string
       *   // Authorization type
       *   type?:"query" | "header"
       *   }
       *   // [title] api package
       *   // package for generated api classes
       *   apiPackage?:string
       *   // [title] Template Version
       *   // template version for generation
       *   templateVersion?:string
       *   // [title] model package
       *   // package for generated models
       *   modelPackage?:string
       *   // [title] model name prefix
       *   // Prefix that will be prepended to all model names. Default is the empty string.
       *   modelNamePrefix?:string
       *   // [title] model name suffix
       *   // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *   modelNameSuffix?:string
       *   // [title] System Properties
       *   // sets specified system properties in key/value format
       *   systemProperties?:Record<string, string>
       *   // [title] instantiation types
       *   // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *   instantiationTypes?:Record<string, string>
       *   // [title] type mappings
       *   // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *   typeMappings?:Record<string, string>
       *   // [title] additional properties
       *   // sets additional properties that can be referenced by the mustache templates in key/value format.
       *   additionalProperties?:Record<string, object>
       *   // [title] language specific primitives
       *   // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *   // [items] start
       *   // [items] end
       *   languageSpecificPrimitives?:(string)[]
       *   // [title] import mappings
       *   // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *   importMappings?:Record<string, string>
       *   // [title] invoker package
       *   // root package for generated code
       *   invokerPackage?:string
       *   // [title] group id
       *   // groupId in generated pom.xml
       *   groupId?:string
       *   // [title] artifact id
       *   // artifactId in generated pom.xml
       *   artifactId?:string
       *   // [title] artifact version
       *   // artifact version generated in pom.xml
       *   artifactVersion?:string
       *   // [title] library
       *   // library template (sub-template)
       *   library?:string
       *   // [title] git user id
       *   // Git user ID, e.g. swagger-api.
       *   gitUserId?:string
       *   // [title] git repo id
       *   // Git repo ID, e.g. swagger-codegen.
       *   gitRepoId?:string
       *   // [title] release note
       *   // Release note, default to 'Minor update'.
       *   releaseNote?:string
       *   // [title] http user agent
       *   // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *   httpUserAgent?:string
       *   // [title] reserved words mappings
       *   // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *   reservedWordsMappings?:Record<string, string>
       *   // [title] ignore file override location
       *   // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *   ignoreFileOverride?:string
       *   // [title] remove prefix of the operationId
       *   // Remove prefix of operationId, e.g. config_getId => getId
       *   removeOperationIdPrefix?:boolean
       *   skipOverride?:boolean
       *   }
       * }
       * ```
       */
      generateBundle<
        Config extends Alova2MethodConfig<GenerationRequest> & {
          data: {
            attr1?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<GenerationRequest, 'clients.generateBundle', Config>;
    };
    documentation: {
      /**
       * ---
       *
       * [GET] Deprecated, use '/{type}/{version}' instead. List generator languages of type 'client' or 'documentation' for given codegen version (defaults to V3)
       *
       * **path:** /clients/suffix
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // client token
       *   token?:string
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // generator version used by codegen engine
       *   version?:"V2" | "V3"
       *   // flag to only return languages of type `client`
       *   clientOnly?:boolean
       *   // client id
       *   id:number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = (string)[]
       * ```
       */
      customClients<
        Config extends Alova2MethodConfig<string[]> & {
          pathParams: {
            /**
             * client token
             */

            token?: string;
          };
          params: {
            /**
             * generator version used by codegen engine
             */

            version?: 'V2' | 'V3';
            /**
             * flag to only return languages of type `client`
             */

            clientOnly?: boolean;
            /**
             * client id
             */

            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<string[], 'documentation.customClients', Config>;
      /**
       * ---
       *
       * [GET] Deprecated, use '/{type}/{version}' instead. List generator languages of type 'documentation' for given codegen version (defaults to V3)
       *
       * **path:** /documentation
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // generator version used by codegen engine
       *   version?:"V2" | "V3"
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   attr1?:string
       *   attr2?:number
       * }
       * ```
       */
      documentationLanguages<
        Config extends Alova2MethodConfig<{
          attr1?: string;
          attr2?: number;
        }> & {
          params: {
            /**
             * generator version used by codegen engine
             */

            version?: 'V2' | 'V3';
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          attr1?: string;
          attr2?: number;
        },
        'documentation.documentationLanguages',
        Config
      >;
    };
  }

  var Apis: Apis;
}

export {};
