/// <reference path="./globals.d.ts1" />
/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Generator - version 3.0.57
 *
 * This is an online swagger codegen server.  You can find out more at https:&#x2F;&#x2F;github.com&#x2F;swagger-api&#x2F;swagger-codegen or on [irc.freenode.net, #swagger](http:&#x2F;&#x2F;swagger.io&#x2F;irc&#x2F;).
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'clients.generateFromURL': ['GET', '/generate'],
  'clients.generate': ['POST', '/generate'],
  'clients.clientLanguages': ['GET', '/clients'],
  'servers.serverLanguages': ['GET', '/servers'],
  'documentation.documentationLanguages': ['GET', '/documentation'],
  'clients.languages': ['GET', '/{type}/{version}'],
  'clients.languagesMulti': ['GET', '/types'],
  'clients.listOptions': ['GET', '/options'],
  'clients.generateBundle': ['POST', '/model'],
  'documentation.renderTemplate': ['POST', '/render']
};
