/* tslint:disable */

/**
 * Nullable Test API - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
/// <reference types='./globals.d.ts' />

const apiDefinitions = {
  'pet.addPet': ['POST', '/pet'],
}

export default apiDefinitions
