/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI - version 1.0.0
 *
 * This is a sample server Petstore server. For this sample, you can use the api key &#x60;special-key&#x60; to test the authorization filters.
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { alovaInstance, $$userConfigMap } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;

type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface Category {
  id?: number;
  name?: string;
  /**
   * Pet Tag
   * ---
   * A tag for a pet
   */

  tag?: Tag;
}
export interface Pet {
  id?: number;
  /**
   * Pet category
   * ---
   * A category for a pet
   */

  category?: Category;
  name: string;
  photoUrls: string[];
  tags?: Tag[];
  /**
   * pet status in the store
   * @deprecated
   */

  status?: 'available' | 'pending' | 'sold';
}
export interface Tag {
  id?: number;
  name?: string;
  pet?: Pet;
}

declare global {
  interface Apis {
    general: {
      /**
       * ---
       *
       * [POST] Add a new pet to the store 2
       *
       * **path:** /pet
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?:number
       *   // [title] Pet category
       *   // A category for a pet
       *   category?:{
       *   id?:number
       *   name?:string
       *   // [title] Pet Tag
       *   // A tag for a pet
       *   tag?:{
       *   id?:number
       *   name?:string
       *   // [cycle] $
       *   pet?:Pet
       *   }
       *   }
       *   name:string
       *   // [items] start
       *   // [items] end
       *   photoUrls:(string)[]
       *   // [items] start
       *   // [title] Pet Tag
       *   // A tag for a pet
       *   // [items] end
       *   tags?:Array<{
       *   id?:number
       *   name?:string
       *   // [cycle] $
       *   pet?:Pet
       *   }>
       *   // pet status in the store
       *   // [deprecated]
       *   status?:"available" | "pending" | "sold"
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   id?:number
       *   // [title] Pet category
       *   // A category for a pet
       *   category?:{
       *   id?:number
       *   name?:string
       *   // [title] Pet Tag
       *   // A tag for a pet
       *   tag?:{
       *   id?:number
       *   name?:string
       *   // [cycle] $
       *   pet?:Pet
       *   }
       *   }
       *   name:string
       *   // [items] start
       *   // [items] end
       *   photoUrls:(string)[]
       *   // [items] start
       *   // [title] Pet Tag
       *   // A tag for a pet
       *   // [items] end
       *   tags?:Array<{
       *   id?:number
       *   name?:string
       *   // [cycle] $
       *   pet?:Pet
       *   }>
       *   // pet status in the store
       *   // [deprecated]
       *   status?:"available" | "pending" | "sold"
       * }
       * ```
       */
      addPet<
        Config extends Alova2MethodConfig<Pet> & {
          data: Pet;
        }
      >(
        config: Config
      ): Alova2Method<Pet, 'general.addPet', Config>;
    };
  }

  var Apis: Apis;
}

export {};
