///<reference path='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Generator - version 3.0.57
 *
 * This is an online swagger codegen server.  You can find out more at https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'clients.generateFromURL': ['GET', '/generate'],
  'servers.generateFromURL': ['GET', '/generate'],
  'documentation.generateFromURL': ['GET', '/generate'],
  'config.generateFromURL': ['GET', '/generate'],
  'clients.generate': ['POST', '/generate'],
  'servers.generate': ['POST', '/generate'],
  'documentation.generate': ['POST', '/generate'],
  'config.generate': ['POST', '/generate'],
  'clients.clientLanguages': ['GET', '/clients'],
  'documentation.clientLanguages': ['GET', '/clients'],
  'servers.serverLanguages': ['GET', '/servers'],
  'documentation.documentationLanguages': ['GET', '/documentation'],
  'clients.languages': ['GET', '/{type}/{version}'],
  'servers.languages': ['GET', '/{type}/{version}'],
  'documentation.languages': ['GET', '/{type}/{version}'],
  'config.languages': ['GET', '/{type}/{version}'],
  'clients.languagesMulti': ['GET', '/types'],
  'servers.languagesMulti': ['GET', '/types'],
  'documentation.languagesMulti': ['GET', '/types'],
  'config.languagesMulti': ['GET', '/types'],
  'clients.listOptions': ['GET', '/options'],
  'servers.listOptions': ['GET', '/options'],
  'documentation.listOptions': ['GET', '/options'],
  'config.listOptions': ['GET', '/options'],
  'documentation.renderTemplate': ['POST', '/render'],
  'clients.generateBundle': ['POST', '/model'],
  'servers.generateBundle': ['POST', '/model'],
  'documentation.generateBundle': ['POST', '/model'],
  'config.generateBundle': ['POST', '/model']
};
