/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Generator - version 3.0.57
 *
 * This is an online swagger codegen server.  You can find out more at https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import { Alova, AlovaMethodCreateConfig, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<any, any, infer RequestConfig, any, infer ResponseHeader>
    ? Omit<AlovaMethodCreateConfig<any, Responded, RequestConfig, ResponseHeader>, 'params'>
    : never;

// Extract the return type of transformData function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transformData'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transformData']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<infer State, infer Export, infer RequestConfig, infer Response, infer ResponseHeader>
    ? Method<
        State,
        Export,
        CurrentConfig extends undefined
          ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
          : CurrentConfig['transformData'] extends (...args: any[]) => any
            ? Awaited<ReturnType<CurrentConfig['transformData']>>
            : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
        any,
        RequestConfig,
        Response,
        ResponseHeader
      >
    : never;

export interface GenerationRequest {
  /**
   * language
   * ---
   * language to generate (required)456
   */
  lang: string;
  /**
   * spec in json format. . Alternative to `specURL`
   */
  spec?: {};
  /**
   * URL of the spec in json format. Alternative to `spec`
   */
  specURL?: string;
  /**
   * type of the spec
   */
  type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG';
  /**
   * codegen version to use
   */
  codegenVersion?: 'V2' | 'V3';
  options?: Options;
}

export interface Options {
  /**
   * authorization
   * ---
   * adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
   */
  auth?: string;
  authorizationValue?: AuthorizationValue;
  /**
   * api package
   * ---
   * package for generated api classes
   */
  apiPackage?: string;
  /**
   * Template Version
   * ---
   * template version for generation
   */
  templateVersion?: string;
  /**
   * model package
   * ---
   * package for generated models
   */
  modelPackage?: string;
  /**
   * model name prefix
   * ---
   * Prefix that will be prepended to all model names. Default is the empty string.
   */
  modelNamePrefix?: string;
  /**
   * model name suffix
   * ---
   * PrefixSuffix that will be appended to all model names. Default is the empty string.
   */
  modelNameSuffix?: string;
  /**
   * System Properties
   * ---
   * sets specified system properties in key/value format
   */
  systemProperties?: {
    [k: string]: string;
  };
  /**
   * instantiation types
   * ---
   * sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
   */
  instantiationTypes?: {
    [k: string]: string;
  };
  /**
   * type mappings
   * ---
   * sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
   */
  typeMappings?: {
    [k: string]: string;
  };
  /**
   * additional properties
   * ---
   * sets additional properties that can be referenced by the mustache templates in key/value format.
   */
  additionalProperties?: {
    [k: string]: {};
  };
  /**
   * language specific primitives
   * ---
   * specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
   */
  languageSpecificPrimitives?: string[];
  /**
   * import mappings
   * ---
   * specifies mappings between a given class and the import that should be used for that class in key/value format.
   */
  importMappings?: {
    [k: string]: string;
  };
  /**
   * invoker package
   * ---
   * root package for generated code
   */
  invokerPackage?: string;
  /**
   * group id
   * ---
   * groupId in generated pom.xml
   */
  groupId?: string;
  /**
   * artifact id
   * ---
   * artifactId in generated pom.xml
   */
  artifactId?: string;
  /**
   * artifact version
   * ---
   * artifact version generated in pom.xml
   */
  artifactVersion?: string;
  /**
   * library
   * ---
   * library template (sub-template)
   */
  library?: string;
  /**
   * git user id
   * ---
   * Git user ID, e.g. swagger-api.
   */
  gitUserId?: string;
  /**
   * git repo id
   * ---
   * Git repo ID, e.g. swagger-codegen.
   */
  gitRepoId?: string;
  /**
   * release note
   * ---
   * Release note, default to 'Minor update'.
   */
  releaseNote?: string;
  /**
   * http user agent
   * ---
   * HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
   */
  httpUserAgent?: string;
  /**
   * reserved words mappings
   * ---
   * pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
   */
  reservedWordsMappings?: {
    [k: string]: string;
  };
  /**
   * ignore file override location
   * ---
   * Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
   */
  ignoreFileOverride?: string;
  /**
   * remove prefix of the operationId
   * ---
   * Remove prefix of operationId, e.g. config_getId => getId
   */
  removeOperationIdPrefix?: boolean;
  skipOverride?: boolean;
}

/**
 * authorization
 * ---
 * adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
 */
export interface AuthorizationValue {
  /**
   * Authorization value
   */
  value?: string;
  /**
   * Authorization key
   */
  keyName?: string;
  /**
   * Authorization type
   */
  type?: 'query' | 'header';
}

export interface RenderRequest {
  /**
   * template
   * ---
   * template as string
   */
  template: string;
  /**
   * context
   * ---
   * context as string
   */
  context: string;
}

export interface CliOption {
  optionName?: string;
  description?: string;
  /**
   * Data type is based on the types supported by the JSON-Schema
   */
  type?: string;
  enum?: {
    [k: string]: string;
  };
  default?: string;
}

export interface RenderResponse {
  value: string;
}

declare global {
  interface APIS {
    clients: {
      /**
       * ---
       *
       * [GET] Generates and download code. GenerationRequest input provided as JSON available at URL specified in parameter codegenOptionsURL.
       *
       * **path:** /generate
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   codegenOptionsURL: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      generateFromURL<Config extends Alova2MethodConfig<string>>(
        config: Config & {
          params: {
            /**
             * [required]
             */
            codegenOptionsURL: string;
          };
        }
      ): Alova2Method<string, 'clients.generateFromURL', Config>;
      /**
       * ---
       *
       * [POST] Generates and download code. GenerationRequest input provided as request body.
       *
       * **path:** /generate
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   codegenOptionsURL: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // language to generate (required)456
       *   // [required]
       *   lang: string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string
       *   // type of the spec
       *   type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG'
       *   // codegen version to use
       *   codegenVersion?: 'V2' | 'V3'
       *   options?: {
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *     auth?: string
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *     authorizationValue?: {
       *       // Authorization value
       *       value?: string
       *       // Authorization key
       *       keyName?: string
       *       // Authorization type
       *       type?: 'query' | 'header'
       *     }
       *     // package for generated api classes
       *     apiPackage?: string
       *     // template version for generation
       *     templateVersion?: string
       *     // package for generated models
       *     modelPackage?: string
       *     // Prefix that will be prepended to all model names. Default is the empty string.
       *     modelNamePrefix?: string
       *     // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *     modelNameSuffix?: string
       *     // sets specified system properties in key/value format
       *     systemProperties?: object
       *     // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *     instantiationTypes?: object
       *     // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *     typeMappings?: object
       *     // sets additional properties that can be referenced by the mustache templates in key/value format.
       *     additionalProperties?: object
       *     // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *     languageSpecificPrimitives?: string[]
       *     // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *     importMappings?: object
       *     // root package for generated code
       *     invokerPackage?: string
       *     // groupId in generated pom.xml
       *     groupId?: string
       *     // artifactId in generated pom.xml
       *     artifactId?: string
       *     // artifact version generated in pom.xml
       *     artifactVersion?: string
       *     // library template (sub-template)
       *     library?: string
       *     // Git user ID, e.g. swagger-api.
       *     gitUserId?: string
       *     // Git repo ID, e.g. swagger-codegen.
       *     gitRepoId?: string
       *     // Release note, default to 'Minor update'.
       *     releaseNote?: string
       *     // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *     httpUserAgent?: string
       *     // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *     reservedWordsMappings?: object
       *     // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *     ignoreFileOverride?: string
       *     // Remove prefix of operationId, e.g. config_getId => getId
       *     removeOperationIdPrefix?: boolean
       *     skipOverride?: boolean
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      generate<Config extends Alova2MethodConfig<string>>(
        config: Config & {
          params: {
            /**
             * [required]
             */
            codegenOptionsURL: string;
          };
          data: GenerationRequest;
        }
      ): Alova2Method<string, 'clients.generate', Config>;
      /**
       * ---
       *
       * [GET] Deprecated, use '/{type}/{version}' instead. List generator languages of type 'client' or 'documentation' for given codegen version (defaults to V3)
       *
       * **path:** /clients
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // generator version used by codegen engine
       *   version?: 'V2' | 'V3'
       *   // flag to only return languages of type `client`
       *   clientOnly?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      clientLanguages<Config extends Alova2MethodConfig<string[]>>(
        config: Config & {
          params: {
            /**
             * generator version used by codegen engine
             */
            version?: 'V2' | 'V3';
            /**
             * flag to only return languages of type `client`
             */
            clientOnly?: boolean;
          };
        }
      ): Alova2Method<string[], 'clients.clientLanguages', Config>;
      /**
       * ---
       *
       * [GET] List generator languages of the given type and version
       *
       * **path:** /{type}/{version}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // generator type
       *   // [required]
       *   type: 'client' | 'server' | 'documentation' | 'config'
       *   // generator version used by codegen engine
       *   // [required]
       *   version: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      languages<Config extends Alova2MethodConfig<string[]>>(
        config: Config & {
          pathParams: {
            /**
             * generator type
             * [required]
             */
            type: 'client' | 'server' | 'documentation' | 'config';
            /**
             * generator version used by codegen engine
             * [required]
             */
            version: 'V2' | 'V3';
          };
        }
      ): Alova2Method<string[], 'clients.languages', Config>;
      /**
       * ---
       *
       * [GET] List generator languages of version defined in 'version parameter (defaults to V3) and type included in 'types' parameter; all languages
       *
       * **path:** /types
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // comma-separated list of generator types
       *   // [required]
       *   types: ('client' | 'server' | 'documentation' | 'config')[]
       *   // generator version used by codegen engine
       *   version?: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      languagesMulti<Config extends Alova2MethodConfig<string[]>>(
        config: Config & {
          params: {
            /**
             * comma-separated list of generator types
             * [required]
             */
            types: ('client' | 'server' | 'documentation' | 'config')[];
            /**
             * generator version used by codegen engine
             */
            version?: 'V2' | 'V3';
          };
        }
      ): Alova2Method<string[], 'clients.languagesMulti', Config>;
      /**
       * ---
       *
       * [GET] Returns options for a given language and version (defaults to V3)
       *
       * **path:** /options
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // language
       *   language?: string
       *   // generator version used by codegen engine
       *   version?: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      listOptions<Config extends Alova2MethodConfig<object>>(
        config: Config & {
          params: {
            /**
             * language
             */
            language?: string;
            /**
             * generator version used by codegen engine
             */
            version?: 'V2' | 'V3';
          };
        }
      ): Alova2Method<object, 'clients.listOptions', Config>;
      /**
       * ---
       *
       * [POST] 你好Generates the intermediate model ("bundle") and returns it as a JSON. body.
       *
       * **path:** /model
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // language to generate (required)456
       *   // [required]
       *   lang: string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string
       *   // type of the spec
       *   type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG'
       *   // codegen version to use
       *   codegenVersion?: 'V2' | 'V3'
       *   options?: {
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *     auth?: string
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *     authorizationValue?: {
       *       // Authorization value
       *       value?: string
       *       // Authorization key
       *       keyName?: string
       *       // Authorization type
       *       type?: 'query' | 'header'
       *     }
       *     // package for generated api classes
       *     apiPackage?: string
       *     // template version for generation
       *     templateVersion?: string
       *     // package for generated models
       *     modelPackage?: string
       *     // Prefix that will be prepended to all model names. Default is the empty string.
       *     modelNamePrefix?: string
       *     // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *     modelNameSuffix?: string
       *     // sets specified system properties in key/value format
       *     systemProperties?: object
       *     // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *     instantiationTypes?: object
       *     // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *     typeMappings?: object
       *     // sets additional properties that can be referenced by the mustache templates in key/value format.
       *     additionalProperties?: object
       *     // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *     languageSpecificPrimitives?: string[]
       *     // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *     importMappings?: object
       *     // root package for generated code
       *     invokerPackage?: string
       *     // groupId in generated pom.xml
       *     groupId?: string
       *     // artifactId in generated pom.xml
       *     artifactId?: string
       *     // artifact version generated in pom.xml
       *     artifactVersion?: string
       *     // library template (sub-template)
       *     library?: string
       *     // Git user ID, e.g. swagger-api.
       *     gitUserId?: string
       *     // Git repo ID, e.g. swagger-codegen.
       *     gitRepoId?: string
       *     // Release note, default to 'Minor update'.
       *     releaseNote?: string
       *     // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *     httpUserAgent?: string
       *     // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *     reservedWordsMappings?: object
       *     // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *     ignoreFileOverride?: string
       *     // Remove prefix of operationId, e.g. config_getId => getId
       *     removeOperationIdPrefix?: boolean
       *     skipOverride?: boolean
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // language to generate (required)456
       *   // [required]
       *   lang: string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string
       *   // type of the spec
       *   type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG'
       *   // codegen version to use
       *   codegenVersion?: 'V2' | 'V3'
       *   options?: {
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *     auth?: string
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *     authorizationValue?: {
       *       // Authorization value
       *       value?: string
       *       // Authorization key
       *       keyName?: string
       *       // Authorization type
       *       type?: 'query' | 'header'
       *     }
       *     // package for generated api classes
       *     apiPackage?: string
       *     // template version for generation
       *     templateVersion?: string
       *     // package for generated models
       *     modelPackage?: string
       *     // Prefix that will be prepended to all model names. Default is the empty string.
       *     modelNamePrefix?: string
       *     // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *     modelNameSuffix?: string
       *     // sets specified system properties in key/value format
       *     systemProperties?: object
       *     // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *     instantiationTypes?: object
       *     // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *     typeMappings?: object
       *     // sets additional properties that can be referenced by the mustache templates in key/value format.
       *     additionalProperties?: object
       *     // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *     languageSpecificPrimitives?: string[]
       *     // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *     importMappings?: object
       *     // root package for generated code
       *     invokerPackage?: string
       *     // groupId in generated pom.xml
       *     groupId?: string
       *     // artifactId in generated pom.xml
       *     artifactId?: string
       *     // artifact version generated in pom.xml
       *     artifactVersion?: string
       *     // library template (sub-template)
       *     library?: string
       *     // Git user ID, e.g. swagger-api.
       *     gitUserId?: string
       *     // Git repo ID, e.g. swagger-codegen.
       *     gitRepoId?: string
       *     // Release note, default to 'Minor update'.
       *     releaseNote?: string
       *     // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *     httpUserAgent?: string
       *     // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *     reservedWordsMappings?: object
       *     // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *     ignoreFileOverride?: string
       *     // Remove prefix of operationId, e.g. config_getId => getId
       *     removeOperationIdPrefix?: boolean
       *     skipOverride?: boolean
       *   }
       * }
       * ```
       */
      generateBundle<Config extends Alova2MethodConfig<GenerationRequest>>(
        config: Config & {
          data: GenerationRequest;
        }
      ): Alova2Method<GenerationRequest, 'clients.generateBundle', Config>;
    };
    servers: {
      /**
       * ---
       *
       * [GET] Generates and download code. GenerationRequest input provided as JSON available at URL specified in parameter codegenOptionsURL.
       *
       * **path:** /generate
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   codegenOptionsURL: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      generateFromURL<Config extends Alova2MethodConfig<string>>(
        config: Config & {
          params: {
            /**
             * [required]
             */
            codegenOptionsURL: string;
          };
        }
      ): Alova2Method<string, 'servers.generateFromURL', Config>;
      /**
       * ---
       *
       * [POST] Generates and download code. GenerationRequest input provided as request body.
       *
       * **path:** /generate
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   codegenOptionsURL: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // language to generate (required)456
       *   // [required]
       *   lang: string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string
       *   // type of the spec
       *   type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG'
       *   // codegen version to use
       *   codegenVersion?: 'V2' | 'V3'
       *   options?: {
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *     auth?: string
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *     authorizationValue?: {
       *       // Authorization value
       *       value?: string
       *       // Authorization key
       *       keyName?: string
       *       // Authorization type
       *       type?: 'query' | 'header'
       *     }
       *     // package for generated api classes
       *     apiPackage?: string
       *     // template version for generation
       *     templateVersion?: string
       *     // package for generated models
       *     modelPackage?: string
       *     // Prefix that will be prepended to all model names. Default is the empty string.
       *     modelNamePrefix?: string
       *     // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *     modelNameSuffix?: string
       *     // sets specified system properties in key/value format
       *     systemProperties?: object
       *     // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *     instantiationTypes?: object
       *     // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *     typeMappings?: object
       *     // sets additional properties that can be referenced by the mustache templates in key/value format.
       *     additionalProperties?: object
       *     // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *     languageSpecificPrimitives?: string[]
       *     // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *     importMappings?: object
       *     // root package for generated code
       *     invokerPackage?: string
       *     // groupId in generated pom.xml
       *     groupId?: string
       *     // artifactId in generated pom.xml
       *     artifactId?: string
       *     // artifact version generated in pom.xml
       *     artifactVersion?: string
       *     // library template (sub-template)
       *     library?: string
       *     // Git user ID, e.g. swagger-api.
       *     gitUserId?: string
       *     // Git repo ID, e.g. swagger-codegen.
       *     gitRepoId?: string
       *     // Release note, default to 'Minor update'.
       *     releaseNote?: string
       *     // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *     httpUserAgent?: string
       *     // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *     reservedWordsMappings?: object
       *     // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *     ignoreFileOverride?: string
       *     // Remove prefix of operationId, e.g. config_getId => getId
       *     removeOperationIdPrefix?: boolean
       *     skipOverride?: boolean
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      generate<Config extends Alova2MethodConfig<string>>(
        config: Config & {
          params: {
            /**
             * [required]
             */
            codegenOptionsURL: string;
          };
          data: GenerationRequest;
        }
      ): Alova2Method<string, 'servers.generate', Config>;
      /**
       * ---
       *
       * [GET] Deprecated, use '/{type}/{version}' instead. List generator languages of type 'server' for given codegen version (defaults to V3)
       *
       * **path:** /servers
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // generator version used by codegen engine
       *   version?: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      serverLanguages<Config extends Alova2MethodConfig<string[]>>(
        config: Config & {
          params: {
            /**
             * generator version used by codegen engine
             */
            version?: 'V2' | 'V3';
          };
        }
      ): Alova2Method<string[], 'servers.serverLanguages', Config>;
      /**
       * ---
       *
       * [GET] List generator languages of the given type and version
       *
       * **path:** /{type}/{version}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // generator type
       *   // [required]
       *   type: 'client' | 'server' | 'documentation' | 'config'
       *   // generator version used by codegen engine
       *   // [required]
       *   version: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      languages<Config extends Alova2MethodConfig<string[]>>(
        config: Config & {
          pathParams: {
            /**
             * generator type
             * [required]
             */
            type: 'client' | 'server' | 'documentation' | 'config';
            /**
             * generator version used by codegen engine
             * [required]
             */
            version: 'V2' | 'V3';
          };
        }
      ): Alova2Method<string[], 'servers.languages', Config>;
      /**
       * ---
       *
       * [GET] List generator languages of version defined in 'version parameter (defaults to V3) and type included in 'types' parameter; all languages
       *
       * **path:** /types
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // comma-separated list of generator types
       *   // [required]
       *   types: ('client' | 'server' | 'documentation' | 'config')[]
       *   // generator version used by codegen engine
       *   version?: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      languagesMulti<Config extends Alova2MethodConfig<string[]>>(
        config: Config & {
          params: {
            /**
             * comma-separated list of generator types
             * [required]
             */
            types: ('client' | 'server' | 'documentation' | 'config')[];
            /**
             * generator version used by codegen engine
             */
            version?: 'V2' | 'V3';
          };
        }
      ): Alova2Method<string[], 'servers.languagesMulti', Config>;
      /**
       * ---
       *
       * [GET] Returns options for a given language and version (defaults to V3)
       *
       * **path:** /options
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // language
       *   language?: string
       *   // generator version used by codegen engine
       *   version?: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      listOptions<Config extends Alova2MethodConfig<object>>(
        config: Config & {
          params: {
            /**
             * language
             */
            language?: string;
            /**
             * generator version used by codegen engine
             */
            version?: 'V2' | 'V3';
          };
        }
      ): Alova2Method<object, 'servers.listOptions', Config>;
      /**
       * ---
       *
       * [POST] 你好Generates the intermediate model ("bundle") and returns it as a JSON. body.
       *
       * **path:** /model
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // language to generate (required)456
       *   // [required]
       *   lang: string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string
       *   // type of the spec
       *   type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG'
       *   // codegen version to use
       *   codegenVersion?: 'V2' | 'V3'
       *   options?: {
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *     auth?: string
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *     authorizationValue?: {
       *       // Authorization value
       *       value?: string
       *       // Authorization key
       *       keyName?: string
       *       // Authorization type
       *       type?: 'query' | 'header'
       *     }
       *     // package for generated api classes
       *     apiPackage?: string
       *     // template version for generation
       *     templateVersion?: string
       *     // package for generated models
       *     modelPackage?: string
       *     // Prefix that will be prepended to all model names. Default is the empty string.
       *     modelNamePrefix?: string
       *     // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *     modelNameSuffix?: string
       *     // sets specified system properties in key/value format
       *     systemProperties?: object
       *     // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *     instantiationTypes?: object
       *     // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *     typeMappings?: object
       *     // sets additional properties that can be referenced by the mustache templates in key/value format.
       *     additionalProperties?: object
       *     // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *     languageSpecificPrimitives?: string[]
       *     // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *     importMappings?: object
       *     // root package for generated code
       *     invokerPackage?: string
       *     // groupId in generated pom.xml
       *     groupId?: string
       *     // artifactId in generated pom.xml
       *     artifactId?: string
       *     // artifact version generated in pom.xml
       *     artifactVersion?: string
       *     // library template (sub-template)
       *     library?: string
       *     // Git user ID, e.g. swagger-api.
       *     gitUserId?: string
       *     // Git repo ID, e.g. swagger-codegen.
       *     gitRepoId?: string
       *     // Release note, default to 'Minor update'.
       *     releaseNote?: string
       *     // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *     httpUserAgent?: string
       *     // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *     reservedWordsMappings?: object
       *     // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *     ignoreFileOverride?: string
       *     // Remove prefix of operationId, e.g. config_getId => getId
       *     removeOperationIdPrefix?: boolean
       *     skipOverride?: boolean
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // language to generate (required)456
       *   // [required]
       *   lang: string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string
       *   // type of the spec
       *   type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG'
       *   // codegen version to use
       *   codegenVersion?: 'V2' | 'V3'
       *   options?: {
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *     auth?: string
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *     authorizationValue?: {
       *       // Authorization value
       *       value?: string
       *       // Authorization key
       *       keyName?: string
       *       // Authorization type
       *       type?: 'query' | 'header'
       *     }
       *     // package for generated api classes
       *     apiPackage?: string
       *     // template version for generation
       *     templateVersion?: string
       *     // package for generated models
       *     modelPackage?: string
       *     // Prefix that will be prepended to all model names. Default is the empty string.
       *     modelNamePrefix?: string
       *     // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *     modelNameSuffix?: string
       *     // sets specified system properties in key/value format
       *     systemProperties?: object
       *     // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *     instantiationTypes?: object
       *     // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *     typeMappings?: object
       *     // sets additional properties that can be referenced by the mustache templates in key/value format.
       *     additionalProperties?: object
       *     // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *     languageSpecificPrimitives?: string[]
       *     // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *     importMappings?: object
       *     // root package for generated code
       *     invokerPackage?: string
       *     // groupId in generated pom.xml
       *     groupId?: string
       *     // artifactId in generated pom.xml
       *     artifactId?: string
       *     // artifact version generated in pom.xml
       *     artifactVersion?: string
       *     // library template (sub-template)
       *     library?: string
       *     // Git user ID, e.g. swagger-api.
       *     gitUserId?: string
       *     // Git repo ID, e.g. swagger-codegen.
       *     gitRepoId?: string
       *     // Release note, default to 'Minor update'.
       *     releaseNote?: string
       *     // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *     httpUserAgent?: string
       *     // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *     reservedWordsMappings?: object
       *     // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *     ignoreFileOverride?: string
       *     // Remove prefix of operationId, e.g. config_getId => getId
       *     removeOperationIdPrefix?: boolean
       *     skipOverride?: boolean
       *   }
       * }
       * ```
       */
      generateBundle<Config extends Alova2MethodConfig<GenerationRequest>>(
        config: Config & {
          data: GenerationRequest;
        }
      ): Alova2Method<GenerationRequest, 'servers.generateBundle', Config>;
    };
    documentation: {
      /**
       * ---
       *
       * [GET] Generates and download code. GenerationRequest input provided as JSON available at URL specified in parameter codegenOptionsURL.
       *
       * **path:** /generate
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   codegenOptionsURL: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      generateFromURL<Config extends Alova2MethodConfig<string>>(
        config: Config & {
          params: {
            /**
             * [required]
             */
            codegenOptionsURL: string;
          };
        }
      ): Alova2Method<string, 'documentation.generateFromURL', Config>;
      /**
       * ---
       *
       * [POST] Generates and download code. GenerationRequest input provided as request body.
       *
       * **path:** /generate
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   codegenOptionsURL: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // language to generate (required)456
       *   // [required]
       *   lang: string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string
       *   // type of the spec
       *   type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG'
       *   // codegen version to use
       *   codegenVersion?: 'V2' | 'V3'
       *   options?: {
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *     auth?: string
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *     authorizationValue?: {
       *       // Authorization value
       *       value?: string
       *       // Authorization key
       *       keyName?: string
       *       // Authorization type
       *       type?: 'query' | 'header'
       *     }
       *     // package for generated api classes
       *     apiPackage?: string
       *     // template version for generation
       *     templateVersion?: string
       *     // package for generated models
       *     modelPackage?: string
       *     // Prefix that will be prepended to all model names. Default is the empty string.
       *     modelNamePrefix?: string
       *     // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *     modelNameSuffix?: string
       *     // sets specified system properties in key/value format
       *     systemProperties?: object
       *     // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *     instantiationTypes?: object
       *     // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *     typeMappings?: object
       *     // sets additional properties that can be referenced by the mustache templates in key/value format.
       *     additionalProperties?: object
       *     // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *     languageSpecificPrimitives?: string[]
       *     // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *     importMappings?: object
       *     // root package for generated code
       *     invokerPackage?: string
       *     // groupId in generated pom.xml
       *     groupId?: string
       *     // artifactId in generated pom.xml
       *     artifactId?: string
       *     // artifact version generated in pom.xml
       *     artifactVersion?: string
       *     // library template (sub-template)
       *     library?: string
       *     // Git user ID, e.g. swagger-api.
       *     gitUserId?: string
       *     // Git repo ID, e.g. swagger-codegen.
       *     gitRepoId?: string
       *     // Release note, default to 'Minor update'.
       *     releaseNote?: string
       *     // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *     httpUserAgent?: string
       *     // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *     reservedWordsMappings?: object
       *     // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *     ignoreFileOverride?: string
       *     // Remove prefix of operationId, e.g. config_getId => getId
       *     removeOperationIdPrefix?: boolean
       *     skipOverride?: boolean
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      generate<Config extends Alova2MethodConfig<string>>(
        config: Config & {
          params: {
            /**
             * [required]
             */
            codegenOptionsURL: string;
          };
          data: GenerationRequest;
        }
      ): Alova2Method<string, 'documentation.generate', Config>;
      /**
       * ---
       *
       * [GET] Deprecated, use '/{type}/{version}' instead. List generator languages of type 'client' or 'documentation' for given codegen version (defaults to V3)
       *
       * **path:** /clients
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // generator version used by codegen engine
       *   version?: 'V2' | 'V3'
       *   // flag to only return languages of type `client`
       *   clientOnly?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      clientLanguages<Config extends Alova2MethodConfig<string[]>>(
        config: Config & {
          params: {
            /**
             * generator version used by codegen engine
             */
            version?: 'V2' | 'V3';
            /**
             * flag to only return languages of type `client`
             */
            clientOnly?: boolean;
          };
        }
      ): Alova2Method<string[], 'documentation.clientLanguages', Config>;
      /**
       * ---
       *
       * [GET] Deprecated, use '/{type}/{version}' instead. List generator languages of type 'documentation' for given codegen version (defaults to V3)
       *
       * **path:** /documentation
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // generator version used by codegen engine
       *   version?: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      documentationLanguages<Config extends Alova2MethodConfig<string[]>>(
        config: Config & {
          params: {
            /**
             * generator version used by codegen engine
             */
            version?: 'V2' | 'V3';
          };
        }
      ): Alova2Method<string[], 'documentation.documentationLanguages', Config>;
      /**
       * ---
       *
       * [GET] List generator languages of the given type and version
       *
       * **path:** /{type}/{version}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // generator type
       *   // [required]
       *   type: 'client' | 'server' | 'documentation' | 'config'
       *   // generator version used by codegen engine
       *   // [required]
       *   version: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      languages<Config extends Alova2MethodConfig<string[]>>(
        config: Config & {
          pathParams: {
            /**
             * generator type
             * [required]
             */
            type: 'client' | 'server' | 'documentation' | 'config';
            /**
             * generator version used by codegen engine
             * [required]
             */
            version: 'V2' | 'V3';
          };
        }
      ): Alova2Method<string[], 'documentation.languages', Config>;
      /**
       * ---
       *
       * [GET] List generator languages of version defined in 'version parameter (defaults to V3) and type included in 'types' parameter; all languages
       *
       * **path:** /types
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // comma-separated list of generator types
       *   // [required]
       *   types: ('client' | 'server' | 'documentation' | 'config')[]
       *   // generator version used by codegen engine
       *   version?: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      languagesMulti<Config extends Alova2MethodConfig<string[]>>(
        config: Config & {
          params: {
            /**
             * comma-separated list of generator types
             * [required]
             */
            types: ('client' | 'server' | 'documentation' | 'config')[];
            /**
             * generator version used by codegen engine
             */
            version?: 'V2' | 'V3';
          };
        }
      ): Alova2Method<string[], 'documentation.languagesMulti', Config>;
      /**
       * ---
       *
       * [GET] Returns options for a given language and version (defaults to V3)
       *
       * **path:** /options
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // language
       *   language?: string
       *   // generator version used by codegen engine
       *   version?: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      listOptions<Config extends Alova2MethodConfig<object>>(
        config: Config & {
          params: {
            /**
             * language
             */
            language?: string;
            /**
             * generator version used by codegen engine
             */
            version?: 'V2' | 'V3';
          };
        }
      ): Alova2Method<object, 'documentation.listOptions', Config>;
      /**
       * ---
       *
       * [POST] 你好Generates the intermediate model ("bundle") and returns it as a JSON. body.
       *
       * **path:** /model
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // language to generate (required)456
       *   // [required]
       *   lang: string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string
       *   // type of the spec
       *   type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG'
       *   // codegen version to use
       *   codegenVersion?: 'V2' | 'V3'
       *   options?: {
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *     auth?: string
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *     authorizationValue?: {
       *       // Authorization value
       *       value?: string
       *       // Authorization key
       *       keyName?: string
       *       // Authorization type
       *       type?: 'query' | 'header'
       *     }
       *     // package for generated api classes
       *     apiPackage?: string
       *     // template version for generation
       *     templateVersion?: string
       *     // package for generated models
       *     modelPackage?: string
       *     // Prefix that will be prepended to all model names. Default is the empty string.
       *     modelNamePrefix?: string
       *     // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *     modelNameSuffix?: string
       *     // sets specified system properties in key/value format
       *     systemProperties?: object
       *     // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *     instantiationTypes?: object
       *     // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *     typeMappings?: object
       *     // sets additional properties that can be referenced by the mustache templates in key/value format.
       *     additionalProperties?: object
       *     // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *     languageSpecificPrimitives?: string[]
       *     // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *     importMappings?: object
       *     // root package for generated code
       *     invokerPackage?: string
       *     // groupId in generated pom.xml
       *     groupId?: string
       *     // artifactId in generated pom.xml
       *     artifactId?: string
       *     // artifact version generated in pom.xml
       *     artifactVersion?: string
       *     // library template (sub-template)
       *     library?: string
       *     // Git user ID, e.g. swagger-api.
       *     gitUserId?: string
       *     // Git repo ID, e.g. swagger-codegen.
       *     gitRepoId?: string
       *     // Release note, default to 'Minor update'.
       *     releaseNote?: string
       *     // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *     httpUserAgent?: string
       *     // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *     reservedWordsMappings?: object
       *     // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *     ignoreFileOverride?: string
       *     // Remove prefix of operationId, e.g. config_getId => getId
       *     removeOperationIdPrefix?: boolean
       *     skipOverride?: boolean
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // language to generate (required)456
       *   // [required]
       *   lang: string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string
       *   // type of the spec
       *   type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG'
       *   // codegen version to use
       *   codegenVersion?: 'V2' | 'V3'
       *   options?: {
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *     auth?: string
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *     authorizationValue?: {
       *       // Authorization value
       *       value?: string
       *       // Authorization key
       *       keyName?: string
       *       // Authorization type
       *       type?: 'query' | 'header'
       *     }
       *     // package for generated api classes
       *     apiPackage?: string
       *     // template version for generation
       *     templateVersion?: string
       *     // package for generated models
       *     modelPackage?: string
       *     // Prefix that will be prepended to all model names. Default is the empty string.
       *     modelNamePrefix?: string
       *     // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *     modelNameSuffix?: string
       *     // sets specified system properties in key/value format
       *     systemProperties?: object
       *     // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *     instantiationTypes?: object
       *     // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *     typeMappings?: object
       *     // sets additional properties that can be referenced by the mustache templates in key/value format.
       *     additionalProperties?: object
       *     // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *     languageSpecificPrimitives?: string[]
       *     // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *     importMappings?: object
       *     // root package for generated code
       *     invokerPackage?: string
       *     // groupId in generated pom.xml
       *     groupId?: string
       *     // artifactId in generated pom.xml
       *     artifactId?: string
       *     // artifact version generated in pom.xml
       *     artifactVersion?: string
       *     // library template (sub-template)
       *     library?: string
       *     // Git user ID, e.g. swagger-api.
       *     gitUserId?: string
       *     // Git repo ID, e.g. swagger-codegen.
       *     gitRepoId?: string
       *     // Release note, default to 'Minor update'.
       *     releaseNote?: string
       *     // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *     httpUserAgent?: string
       *     // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *     reservedWordsMappings?: object
       *     // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *     ignoreFileOverride?: string
       *     // Remove prefix of operationId, e.g. config_getId => getId
       *     removeOperationIdPrefix?: boolean
       *     skipOverride?: boolean
       *   }
       * }
       * ```
       */
      generateBundle<Config extends Alova2MethodConfig<GenerationRequest>>(
        config: Config & {
          data: GenerationRequest;
        }
      ): Alova2Method<GenerationRequest, 'documentation.generateBundle', Config>;
      /**
       * ---
       *
       * [POST] render a template using the provided data
       *
       * **path:** /render
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // template as string
       *   // [required]
       *   template: string
       *   // context as string
       *   // [required]
       *   context: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      renderTemplate<Config extends Alova2MethodConfig<unknown>>(
        config: Config & {
          data: RenderRequest;
        }
      ): Alova2Method<unknown, 'documentation.renderTemplate', Config>;
    };
    config: {
      /**
       * ---
       *
       * [GET] Generates and download code. GenerationRequest input provided as JSON available at URL specified in parameter codegenOptionsURL.
       *
       * **path:** /generate
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   codegenOptionsURL: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      generateFromURL<Config extends Alova2MethodConfig<string>>(
        config: Config & {
          params: {
            /**
             * [required]
             */
            codegenOptionsURL: string;
          };
        }
      ): Alova2Method<string, 'config.generateFromURL', Config>;
      /**
       * ---
       *
       * [POST] Generates and download code. GenerationRequest input provided as request body.
       *
       * **path:** /generate
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // [required]
       *   codegenOptionsURL: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // language to generate (required)456
       *   // [required]
       *   lang: string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string
       *   // type of the spec
       *   type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG'
       *   // codegen version to use
       *   codegenVersion?: 'V2' | 'V3'
       *   options?: {
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *     auth?: string
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *     authorizationValue?: {
       *       // Authorization value
       *       value?: string
       *       // Authorization key
       *       keyName?: string
       *       // Authorization type
       *       type?: 'query' | 'header'
       *     }
       *     // package for generated api classes
       *     apiPackage?: string
       *     // template version for generation
       *     templateVersion?: string
       *     // package for generated models
       *     modelPackage?: string
       *     // Prefix that will be prepended to all model names. Default is the empty string.
       *     modelNamePrefix?: string
       *     // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *     modelNameSuffix?: string
       *     // sets specified system properties in key/value format
       *     systemProperties?: object
       *     // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *     instantiationTypes?: object
       *     // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *     typeMappings?: object
       *     // sets additional properties that can be referenced by the mustache templates in key/value format.
       *     additionalProperties?: object
       *     // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *     languageSpecificPrimitives?: string[]
       *     // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *     importMappings?: object
       *     // root package for generated code
       *     invokerPackage?: string
       *     // groupId in generated pom.xml
       *     groupId?: string
       *     // artifactId in generated pom.xml
       *     artifactId?: string
       *     // artifact version generated in pom.xml
       *     artifactVersion?: string
       *     // library template (sub-template)
       *     library?: string
       *     // Git user ID, e.g. swagger-api.
       *     gitUserId?: string
       *     // Git repo ID, e.g. swagger-codegen.
       *     gitRepoId?: string
       *     // Release note, default to 'Minor update'.
       *     releaseNote?: string
       *     // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *     httpUserAgent?: string
       *     // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *     reservedWordsMappings?: object
       *     // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *     ignoreFileOverride?: string
       *     // Remove prefix of operationId, e.g. config_getId => getId
       *     removeOperationIdPrefix?: boolean
       *     skipOverride?: boolean
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       */
      generate<Config extends Alova2MethodConfig<string>>(
        config: Config & {
          params: {
            /**
             * [required]
             */
            codegenOptionsURL: string;
          };
          data: GenerationRequest;
        }
      ): Alova2Method<string, 'config.generate', Config>;
      /**
       * ---
       *
       * [GET] List generator languages of the given type and version
       *
       * **path:** /{type}/{version}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // generator type
       *   // [required]
       *   type: 'client' | 'server' | 'documentation' | 'config'
       *   // generator version used by codegen engine
       *   // [required]
       *   version: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      languages<Config extends Alova2MethodConfig<string[]>>(
        config: Config & {
          pathParams: {
            /**
             * generator type
             * [required]
             */
            type: 'client' | 'server' | 'documentation' | 'config';
            /**
             * generator version used by codegen engine
             * [required]
             */
            version: 'V2' | 'V3';
          };
        }
      ): Alova2Method<string[], 'config.languages', Config>;
      /**
       * ---
       *
       * [GET] List generator languages of version defined in 'version parameter (defaults to V3) and type included in 'types' parameter; all languages
       *
       * **path:** /types
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // comma-separated list of generator types
       *   // [required]
       *   types: ('client' | 'server' | 'documentation' | 'config')[]
       *   // generator version used by codegen engine
       *   version?: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string[]
       * ```
       */
      languagesMulti<Config extends Alova2MethodConfig<string[]>>(
        config: Config & {
          params: {
            /**
             * comma-separated list of generator types
             * [required]
             */
            types: ('client' | 'server' | 'documentation' | 'config')[];
            /**
             * generator version used by codegen engine
             */
            version?: 'V2' | 'V3';
          };
        }
      ): Alova2Method<string[], 'config.languagesMulti', Config>;
      /**
       * ---
       *
       * [GET] Returns options for a given language and version (defaults to V3)
       *
       * **path:** /options
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // language
       *   language?: string
       *   // generator version used by codegen engine
       *   version?: 'V2' | 'V3'
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      listOptions<Config extends Alova2MethodConfig<object>>(
        config: Config & {
          params: {
            /**
             * language
             */
            language?: string;
            /**
             * generator version used by codegen engine
             */
            version?: 'V2' | 'V3';
          };
        }
      ): Alova2Method<object, 'config.listOptions', Config>;
      /**
       * ---
       *
       * [POST] 你好Generates the intermediate model ("bundle") and returns it as a JSON. body.
       *
       * **path:** /model
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // language to generate (required)456
       *   // [required]
       *   lang: string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string
       *   // type of the spec
       *   type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG'
       *   // codegen version to use
       *   codegenVersion?: 'V2' | 'V3'
       *   options?: {
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *     auth?: string
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *     authorizationValue?: {
       *       // Authorization value
       *       value?: string
       *       // Authorization key
       *       keyName?: string
       *       // Authorization type
       *       type?: 'query' | 'header'
       *     }
       *     // package for generated api classes
       *     apiPackage?: string
       *     // template version for generation
       *     templateVersion?: string
       *     // package for generated models
       *     modelPackage?: string
       *     // Prefix that will be prepended to all model names. Default is the empty string.
       *     modelNamePrefix?: string
       *     // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *     modelNameSuffix?: string
       *     // sets specified system properties in key/value format
       *     systemProperties?: object
       *     // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *     instantiationTypes?: object
       *     // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *     typeMappings?: object
       *     // sets additional properties that can be referenced by the mustache templates in key/value format.
       *     additionalProperties?: object
       *     // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *     languageSpecificPrimitives?: string[]
       *     // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *     importMappings?: object
       *     // root package for generated code
       *     invokerPackage?: string
       *     // groupId in generated pom.xml
       *     groupId?: string
       *     // artifactId in generated pom.xml
       *     artifactId?: string
       *     // artifact version generated in pom.xml
       *     artifactVersion?: string
       *     // library template (sub-template)
       *     library?: string
       *     // Git user ID, e.g. swagger-api.
       *     gitUserId?: string
       *     // Git repo ID, e.g. swagger-codegen.
       *     gitRepoId?: string
       *     // Release note, default to 'Minor update'.
       *     releaseNote?: string
       *     // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *     httpUserAgent?: string
       *     // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *     reservedWordsMappings?: object
       *     // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *     ignoreFileOverride?: string
       *     // Remove prefix of operationId, e.g. config_getId => getId
       *     removeOperationIdPrefix?: boolean
       *     skipOverride?: boolean
       *   }
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // language to generate (required)456
       *   // [required]
       *   lang: string
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string
       *   // type of the spec
       *   type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG'
       *   // codegen version to use
       *   codegenVersion?: 'V2' | 'V3'
       *   options?: {
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
       *     auth?: string
       *     // adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
       *     authorizationValue?: {
       *       // Authorization value
       *       value?: string
       *       // Authorization key
       *       keyName?: string
       *       // Authorization type
       *       type?: 'query' | 'header'
       *     }
       *     // package for generated api classes
       *     apiPackage?: string
       *     // template version for generation
       *     templateVersion?: string
       *     // package for generated models
       *     modelPackage?: string
       *     // Prefix that will be prepended to all model names. Default is the empty string.
       *     modelNamePrefix?: string
       *     // PrefixSuffix that will be appended to all model names. Default is the empty string.
       *     modelNameSuffix?: string
       *     // sets specified system properties in key/value format
       *     systemProperties?: object
       *     // sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
       *     instantiationTypes?: object
       *     // sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
       *     typeMappings?: object
       *     // sets additional properties that can be referenced by the mustache templates in key/value format.
       *     additionalProperties?: object
       *     // specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
       *     languageSpecificPrimitives?: string[]
       *     // specifies mappings between a given class and the import that should be used for that class in key/value format.
       *     importMappings?: object
       *     // root package for generated code
       *     invokerPackage?: string
       *     // groupId in generated pom.xml
       *     groupId?: string
       *     // artifactId in generated pom.xml
       *     artifactId?: string
       *     // artifact version generated in pom.xml
       *     artifactVersion?: string
       *     // library template (sub-template)
       *     library?: string
       *     // Git user ID, e.g. swagger-api.
       *     gitUserId?: string
       *     // Git repo ID, e.g. swagger-codegen.
       *     gitRepoId?: string
       *     // Release note, default to 'Minor update'.
       *     releaseNote?: string
       *     // HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
       *     httpUserAgent?: string
       *     // pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
       *     reservedWordsMappings?: object
       *     // Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
       *     ignoreFileOverride?: string
       *     // Remove prefix of operationId, e.g. config_getId => getId
       *     removeOperationIdPrefix?: boolean
       *     skipOverride?: boolean
       *   }
       * }
       * ```
       */
      generateBundle<Config extends Alova2MethodConfig<GenerationRequest>>(
        config: Config & {
          data: GenerationRequest;
        }
      ): Alova2Method<GenerationRequest, 'config.generateBundle', Config>;
    };
  }

  var Apis: APIS;
}
