/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 接口文档 公共/第三方 - version 0.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
module.exports = {
  'Dept.post_api_dept_add': ['POST', '/api/Dept/Add'],
  'Dept.delete_api_dept_delete': ['DELETE', '/api/Dept/Delete'],
  'Dept.post_api_dept_download': ['POST', '/api/Dept/Download'],
  'Dept.get_api_dept_getinfo': ['GET', '/api/Dept/GetInfo'],
  'Dept.get_api_dept_getlist': ['GET', '/api/Dept/GetList'],
  'Dept.get_api_dept_select': ['GET', '/api/Dept/Select'],
  'Dept.put_api_dept_update': ['PUT', '/api/Dept/Update']
};
