///<reference path='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Generator - version 3.0.57
 *
 * This is an online swagger codegen server.  You can find out more at https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'clients.generateFromURL': ['GET', 'xxx1'],
  'servers.generateFromURL': ['GET', 'xxx1'],
  'documentation.generateFromURL': ['GET', 'xxx1'],
  'config.generateFromURL': ['GET', 'xxx1'],
  'clients.generate': ['POST', 'xxx1'],
  'servers.generate': ['POST', 'xxx1'],
  'documentation.generate': ['POST', 'xxx1'],
  'config.generate': ['POST', 'xxx1']
};
