/// <reference path="./globals.d.ts" />
/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Petstore - version 1.0.0
 * This is a sample server Petstore server. For this sample, you can use the api key
    `special-key` to test the authorization filters.
 *
 * OpenAPI version: 3.0.0
 * Contact: apiteam@swagger.io123
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 * https://github.com/alovajs/devtools.git
 * Do not edit the file manually.
 */
export default {
  'user.userLogin': ['POST', '/user/login'],
  'pet.getPetById': ['GET', '/pet/{petId}']
};
