/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Generator - version 3.0.57
 *
 * This is an online swagger codegen server.  You can find out more at https://github.com/swagger-api/swagger-codegen or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import { Alova, AlovaMethodCreateConfig, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded, Parameters = Record<string, any>> =
  CollapsedAlova extends Alova<any, any, infer RequestConfig, any, infer ResponseHeader>
    ? AlovaMethodCreateConfig<any, Responded, RequestConfig, ResponseHeader> & {
        params: Parameters;
      }
    : never;

// Extract the return type of transformData function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transformData'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transformData']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<infer State, infer Export, infer RequestConfig, infer Response, infer ResponseHeader>
    ? Method<
        State,
        Export,
        CurrentConfig extends undefined
          ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
          : CurrentConfig['transformData'] extends (...args: any[]) => any
            ? Awaited<ReturnType<CurrentConfig['transformData']>>
            : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
        any,
        RequestConfig,
        Response,
        ResponseHeader
      >
    : never;

export interface GenerationRequest {
  /**
   * language
   * ---
   * language to generate (required)
   */
  lang: string;
  /**
   * spec in json format. . Alternative to `specURL`
   */
  spec?: {};
  /**
   * URL of the spec in json format. Alternative to `spec`
   */
  specURL?: string;
  /**
   * type of the spec
   */
  type?: 'CLIENT' | 'SERVER' | 'DOCUMENTATION' | 'CONFIG';
  /**
   * codegen version to use
   */
  codegenVersion?: 'V2' | 'V3';
  options?: Options;
}
export interface Options {
  /**
   * authorization
   * ---
   * adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
   */
  auth?: string;
  authorizationValue?: AuthorizationValue;
  /**
   * api package
   * ---
   * package for generated api classes
   */
  apiPackage?: string;
  /**
   * Template Version
   * ---
   * template version for generation
   */
  templateVersion?: string;
  /**
   * model package
   * ---
   * package for generated models
   */
  modelPackage?: string;
  /**
   * model name prefix
   * ---
   * Prefix that will be prepended to all model names. Default is the empty string.
   */
  modelNamePrefix?: string;
  /**
   * model name suffix
   * ---
   * PrefixSuffix that will be appended to all model names. Default is the empty string.
   */
  modelNameSuffix?: string;
  /**
   * System Properties
   * ---
   * sets specified system properties in key/value format
   */
  systemProperties?: {
    [k: string]: string;
  };
  /**
   * instantiation types
   * ---
   * sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
   */
  instantiationTypes?: {
    [k: string]: string;
  };
  /**
   * type mappings
   * ---
   * sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
   */
  typeMappings?: {
    [k: string]: string;
  };
  /**
   * additional properties
   * ---
   * sets additional properties that can be referenced by the mustache templates in key/value format.
   */
  additionalProperties?: {
    [k: string]: {};
  };
  /**
   * language specific primitives
   * ---
   * specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
   */
  languageSpecificPrimitives?: string[];
  /**
   * import mappings
   * ---
   * specifies mappings between a given class and the import that should be used for that class in key/value format.
   */
  importMappings?: {
    [k: string]: string;
  };
  /**
   * invoker package
   * ---
   * root package for generated code
   */
  invokerPackage?: string;
  /**
   * group id
   * ---
   * groupId in generated pom.xml
   */
  groupId?: string;
  /**
   * artifact id
   * ---
   * artifactId in generated pom.xml
   */
  artifactId?: string;
  /**
   * artifact version
   * ---
   * artifact version generated in pom.xml
   */
  artifactVersion?: string;
  /**
   * library
   * ---
   * library template (sub-template)
   */
  library?: string;
  /**
   * git user id
   * ---
   * Git user ID, e.g. swagger-api.
   */
  gitUserId?: string;
  /**
   * git repo id
   * ---
   * Git repo ID, e.g. swagger-codegen.
   */
  gitRepoId?: string;
  /**
   * release note
   * ---
   * Release note, default to 'Minor update'.
   */
  releaseNote?: string;
  /**
   * http user agent
   * ---
   * HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
   */
  httpUserAgent?: string;
  /**
   * reserved words mappings
   * ---
   * pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
   */
  reservedWordsMappings?: {
    [k: string]: string;
  };
  /**
   * ignore file override location
   * ---
   * Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
   */
  ignoreFileOverride?: string;
  /**
   * remove prefix of the operationId
   * ---
   * Remove prefix of operationId, e.g. config_getId => getId
   */
  removeOperationIdPrefix?: boolean;
  skipOverride?: boolean;
}
/**
 * authorization
 * ---
 * adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
 */
export interface AuthorizationValue {
  /**
   * Authorization value
   */
  value?: string;
  /**
   * Authorization key
   */
  keyName?: string;
  /**
   * Authorization type
   */
  type?: 'query' | 'header';
}

/**
 * authorization
 * ---
 * adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
 */
export interface AuthorizationValue {
  /**
   * Authorization value
   */
  value?: string;
  /**
   * Authorization key
   */
  keyName?: string;
  /**
   * Authorization type
   */
  type?: 'query' | 'header';
}

export interface Options {
  /**
   * authorization
   * ---
   * adds authorization headers when fetching the open api definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values
   */
  auth?: string;
  authorizationValue?: AuthorizationValue;
  /**
   * api package
   * ---
   * package for generated api classes
   */
  apiPackage?: string;
  /**
   * Template Version
   * ---
   * template version for generation
   */
  templateVersion?: string;
  /**
   * model package
   * ---
   * package for generated models
   */
  modelPackage?: string;
  /**
   * model name prefix
   * ---
   * Prefix that will be prepended to all model names. Default is the empty string.
   */
  modelNamePrefix?: string;
  /**
   * model name suffix
   * ---
   * PrefixSuffix that will be appended to all model names. Default is the empty string.
   */
  modelNameSuffix?: string;
  /**
   * System Properties
   * ---
   * sets specified system properties in key/value format
   */
  systemProperties?: {
    [k: string]: string;
  };
  /**
   * instantiation types
   * ---
   * sets instantiation type mappings in key/value format. For example (in Java): array=ArrayList,map=HashMap. In other words array types will get instantiated as ArrayList in generated code.
   */
  instantiationTypes?: {
    [k: string]: string;
  };
  /**
   * type mappings
   * ---
   * sets mappings between swagger spec types and generated code types in key/value format. For example: array=List,map=Map,string=String.
   */
  typeMappings?: {
    [k: string]: string;
  };
  /**
   * additional properties
   * ---
   * sets additional properties that can be referenced by the mustache templates in key/value format.
   */
  additionalProperties?: {
    [k: string]: {};
  };
  /**
   * language specific primitives
   * ---
   * specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double. You can also have multiple occurrences of this option.
   */
  languageSpecificPrimitives?: string[];
  /**
   * import mappings
   * ---
   * specifies mappings between a given class and the import that should be used for that class in key/value format.
   */
  importMappings?: {
    [k: string]: string;
  };
  /**
   * invoker package
   * ---
   * root package for generated code
   */
  invokerPackage?: string;
  /**
   * group id
   * ---
   * groupId in generated pom.xml
   */
  groupId?: string;
  /**
   * artifact id
   * ---
   * artifactId in generated pom.xml
   */
  artifactId?: string;
  /**
   * artifact version
   * ---
   * artifact version generated in pom.xml
   */
  artifactVersion?: string;
  /**
   * library
   * ---
   * library template (sub-template)
   */
  library?: string;
  /**
   * git user id
   * ---
   * Git user ID, e.g. swagger-api.
   */
  gitUserId?: string;
  /**
   * git repo id
   * ---
   * Git repo ID, e.g. swagger-codegen.
   */
  gitRepoId?: string;
  /**
   * release note
   * ---
   * Release note, default to 'Minor update'.
   */
  releaseNote?: string;
  /**
   * http user agent
   * ---
   * HTTP user agent, e.g. codegen_csharp_api_client, default to 'Swagger-Codegen/{packageVersion}}/{language}'
   */
  httpUserAgent?: string;
  /**
   * reserved words mappings
   * ---
   * pecifies how a reserved name should be escaped to. Otherwise, the default _<name> is used. For example id=identifier.
   */
  reservedWordsMappings?: {
    [k: string]: string;
  };
  /**
   * ignore file override location
   * ---
   * Specifies an override location for the .swagger-codegen-ignore file. Most useful on initial generation.
   */
  ignoreFileOverride?: string;
  /**
   * remove prefix of the operationId
   * ---
   * Remove prefix of operationId, e.g. config_getId => getId
   */
  removeOperationIdPrefix?: boolean;
  skipOverride?: boolean;
}
/**
 * authorization
 * ---
 * adds authorization headers when fetching the open api definitions remotely. Pass in an authorizationValue object
 */
export interface AuthorizationValue {
  /**
   * Authorization value
   */
  value?: string;
  /**
   * Authorization key
   */
  keyName?: string;
  /**
   * Authorization type
   */
  type?: 'query' | 'header';
}

export interface CliOption {
  optionName?: string;
  description?: string;
  /**
   * Data type is based on the types supported by the JSON-Schema
   */
  type?: string;
  enum?: {
    [k: string]: string;
  };
  default?: string;
}

export interface RenderRequest {
  /**
   * template
   * ---
   * template as string
   */
  template: string;
  /**
   * context
   * ---
   * context as string
   */
  context: string;
}

export interface RenderResponse {
  value: string;
}

declare global {
  interface APIS {
    clients: {
      /**
       * ---
       *
       * [GET]Generates and download code. GenerationRequest input provided as JSON available at URL specified in parameter codegenOptionsURL.
       *
       * **path:** xxx1
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       *
       * ---
       */
      generateFromURL<Config extends Alova2MethodConfig<string>>(
        config?: Alova2MethodConfig<string> & {}
      ): Alova2Method<string, 'clients.generateFromURL', Config>;
      /**
       * ---
       *
       * [POST]Generates and download code. GenerationRequest input provided as request body.
       *
       * **path:** xxx1
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * interface RequestBody {
       *   // language to generate (required)
       *   lang?: string;
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object;
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string;
       *   // codegen version to use
       *   codegenVersion?: string;
       *   //
       *   options?: Options;
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       *
       * ---
       */
      generate<Config extends Alova2MethodConfig<string>>(
        config?: Alova2MethodConfig<string> & {
          data: {
            /**
             *language to generate (required)
             */
            lang?: string;
            /**
             *spec in json format. . Alternative to `specURL`
             */
            spec?: object;
            /**
             *URL of the spec in json format. Alternative to `spec`
             */
            specURL?: string;
            /**
             *codegen version to use
             */
            codegenVersion?: string;
            options?: Options;
          };
        }
      ): Alova2Method<string, 'clients.generate', Config>;
    };
    servers: {
      /**
       * ---
       *
       * [GET]Generates and download code. GenerationRequest input provided as JSON available at URL specified in parameter codegenOptionsURL.
       *
       * **path:** xxx1
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       *
       * ---
       */
      generateFromURL<Config extends Alova2MethodConfig<string>>(
        config?: Alova2MethodConfig<string> & {}
      ): Alova2Method<string, 'servers.generateFromURL', Config>;
      /**
       * ---
       *
       * [POST]Generates and download code. GenerationRequest input provided as request body.
       *
       * **path:** xxx1
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * interface RequestBody {
       *   // language to generate (required)
       *   lang?: string;
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object;
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string;
       *   // codegen version to use
       *   codegenVersion?: string;
       *   //
       *   options?: Options;
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       *
       * ---
       */
      generate<Config extends Alova2MethodConfig<string>>(
        config?: Alova2MethodConfig<string> & {
          data: {
            /**
             *language to generate (required)
             */
            lang?: string;
            /**
             *spec in json format. . Alternative to `specURL`
             */
            spec?: object;
            /**
             *URL of the spec in json format. Alternative to `spec`
             */
            specURL?: string;
            /**
             *codegen version to use
             */
            codegenVersion?: string;
            options?: Options;
          };
        }
      ): Alova2Method<string, 'servers.generate', Config>;
    };
    documentation: {
      /**
       * ---
       *
       * [GET]Generates and download code. GenerationRequest input provided as JSON available at URL specified in parameter codegenOptionsURL.
       *
       * **path:** xxx1
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       *
       * ---
       */
      generateFromURL<Config extends Alova2MethodConfig<string>>(
        config?: Alova2MethodConfig<string> & {}
      ): Alova2Method<string, 'documentation.generateFromURL', Config>;
      /**
       * ---
       *
       * [POST]Generates and download code. GenerationRequest input provided as request body.
       *
       * **path:** xxx1
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * interface RequestBody {
       *   // language to generate (required)
       *   lang?: string;
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object;
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string;
       *   // codegen version to use
       *   codegenVersion?: string;
       *   //
       *   options?: Options;
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       *
       * ---
       */
      generate<Config extends Alova2MethodConfig<string>>(
        config?: Alova2MethodConfig<string> & {
          data: {
            /**
             *language to generate (required)
             */
            lang?: string;
            /**
             *spec in json format. . Alternative to `specURL`
             */
            spec?: object;
            /**
             *URL of the spec in json format. Alternative to `spec`
             */
            specURL?: string;
            /**
             *codegen version to use
             */
            codegenVersion?: string;
            options?: Options;
          };
        }
      ): Alova2Method<string, 'documentation.generate', Config>;
    };
    config: {
      /**
       * ---
       *
       * [GET]Generates and download code. GenerationRequest input provided as JSON available at URL specified in parameter codegenOptionsURL.
       *
       * **path:** xxx1
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       *
       * ---
       */
      generateFromURL<Config extends Alova2MethodConfig<string>>(
        config?: Alova2MethodConfig<string> & {}
      ): Alova2Method<string, 'config.generateFromURL', Config>;
      /**
       * ---
       *
       * [POST]Generates and download code. GenerationRequest input provided as request body.
       *
       * **path:** xxx1
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * interface RequestBody {
       *   // language to generate (required)
       *   lang?: string;
       *   // spec in json format. . Alternative to `specURL`
       *   spec?: object;
       *   // URL of the spec in json format. Alternative to `spec`
       *   specURL?: string;
       *   // codegen version to use
       *   codegenVersion?: string;
       *   //
       *   options?: Options;
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = string
       * ```
       *
       * ---
       */
      generate<Config extends Alova2MethodConfig<string>>(
        config?: Alova2MethodConfig<string> & {
          data: {
            /**
             *language to generate (required)
             */
            lang?: string;
            /**
             *spec in json format. . Alternative to `specURL`
             */
            spec?: object;
            /**
             *URL of the spec in json format. Alternative to `spec`
             */
            specURL?: string;
            /**
             *codegen version to use
             */
            codegenVersion?: string;
            options?: Options;
          };
        }
      ): Alova2Method<string, 'config.generate', Config>;
    };
  }

  var Apis: APIS;
}
