/* tslint:disable */

/**
 * OpenAPI - version 1.0.0
 *
 * This is a sample server Petstore server. For this sample, you can use the api key &#x60;special-key&#x60; to test the authorization filters.
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
/// <reference types='./globals.d.ts' />

const apiDefinitions = {
  'Apis.general.addPet': ['POST', '/pet'],
} as const

export default apiDefinitions
